theme: jekyll-theme-minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Scoria]
description: [An international, collaborative BSc/MSc thesis project to create an open-source music scorification pipeline]