title: Scoria
logo: /assets/img/logo-project.pngs
description: An international, collaborative BSc/MSc thesis project to create an open-source music scorification pipeline
show_downloads: true
theme: jekyll-theme-minimal